### PR TITLE
Add ability to use Lazy GM's encounter difficulty system

### LINKED ISSUE #114: [Feature Request]: Allow other methods to calculate Deadly Encounters
I had the thought of a FR for initiative tracker. Would it be possible to allow us to use a different calculation for Deadly encounter difficulty?

Specifically, the The Lazy GM method of encounter benchmark (as seen on https://slyflourish.com/the_lazy_encounter_benchmark.html) is simplified to make it easier for the GM to calculate out interesting and a bit more difficult encounters. This only calculates the "Deadly" encounters, because being a lazy GM, who would invest the time to find an "Easy" one?. The math is the following:

Tier 1 PCs [levels 1-4]: (Sum of Player Levels) / Nr. of Players / 4 = Deadly encounter total CR monsters
All other tiers [levels 5-20]: (Sum of Player Levels) / Nr. of Players / 2 = Deadly encounter total CR monsters
I would love to have an option or method to call out to use the "Lazy GM" option which would recalculate the Deadly Encounter using his method vs. that of the DMG.

p.s. Sorry for the wrong post in the other repository.

### PR DESCRIPTION
**Pull request by miscoined**
This adds a setting for XP system which currently has two options: DnD 5e (the default, current behavior), and DnD 5e Lazy GM, which uses a CR-based calculation.

Resolves #114 .

This also allows additional XP systems to be added in the future. I've gotten a Pathfinder 2E XP system working in the encounter builder which I'll be sending a PR along for when this one gets merged :)

I did my best to avoid any breaking API changes. Any existing integrations should still work provided the XP system is set to `dnd5e`, although this comes with the unfortunate effect of `totalXp` having a different meaning between XP systems. Any existing integrations which read the difficulty report will probably break if they're set to any other XP system.

### CODE REVIEW

**Comment by valentine195** [comment]
@miscoined I think this is a great start and I really appreciate the effort put in here. I'm thinking about how to make it easier to add in new systems later.

1. I think a new folder structure, with a folder-per-system inside it and then the common utilities at the top level, would be easier to maintain and add onto.
2. Possibly hard-typing the Threshold system and creating a new function that returns the threshold for a given difficulty would be more readable than calculating it in the Svelte component.
3. Same for xp as above.
4. I'm wondering if it would be better to make system-specific Svelte components anyway. As additional systems are added, this component will get massive.

I am also wondering if a difficulty service that the component interfaces with would be better, with standard methods. Then new systems would just need to hook into those. Thoughts?

**Comment by miscoined** [comment]
Hey, thanks for the fast review, and for the feedback! I'm very much in the 'enthusiastic learner' category when it comes to JS/Svelte/Typescript, so apologies if I struggle with terminology a bit.

1. Strong agree with a new folder structure. I started adding in the PF2e one today and yeah, at the very least a new file per-system is required.
2. I'm not sure what you mean by 'hard-typing' here, sorry. Currently the difficulty threshold (e.g. "Deadly") for the actual XP amount comes directly from the difficulty report, but we'll still need to list out the budgets for the encounter builder.
3. As above- I'm not sure what XP calculation you're referring to, afaict the only XP related calculations happening in the component is the conversion to string
4. I was thinking about system-specific Svelte components as well. I think it depends a little on the expected use-cases; if it's mostly things that are more-or-less XP-based systems then I don't imagine there'll be much custom layout stuff required. My TTRPG experience here is pretty limited on the kinds of things that might come up here.

Terminology strikes again; by a difficulty service, are you referring to eg a base class that has a bunch of defined methods, and then every new system would be a subclass? if so then I think that could work well, but that could just be my OOP bias talking.

For now I'll have a look at at least separating out the different subsystems a bit.

A question, also; do I need to be careful about breaking changes to the API? I've been trying to keep it as untouched as possible, but it'd be good to know the likelihood of changes in the APIs difficulty reports breaking anyone's integrations.

**Comment by valentine195** [comment]
> By a difficulty service, are you referring to eg a base class that has a bunch of defined methods, and then every new system would be a subclass? if so then I think that could work well, but that could just be my OOP bias talking.

Yes, essentially

2 / 3:

By hard typing, I mean: enforce `type Threshold = [string, string][];` and move the threshold calculation to its own function outside the Svelte component:
```ts
export function getThresholds(difficulty: Difficulty): Thresholds {
    switch (difficulty.system) ...
}
```

That will help declutter the Svelte component, although if we implement a difficulty service then this can wrap into that anyway.

**Comment by miscoined** [comment]
Added back in the Lazy GM system. Apologies for the messy commits also; let me know if you'd like me to just squash em all into one, or leave adding in the new system as a separate PR. I'm fairly new to working with pull requests, sorry!

**Comment by valentine195** [comment]
@miscoined thanks! I glanced through the code on the web and it looks a lot more extensible, thanks.

I'll try to pull this code and do some testing.

**Comment by valentine195** [comment]
I’m going to try to review this today

**Pull request merged**
