### PR TITLE
feat: Temporarily change AC on the fly

### PR DESCRIPTION
**Pull request by SondreElg**
By clicking on the AC field of creatures you can type a new value directly in. Values differing from the creatures' original AC will be shown in **bold**, and hovering will display a label with the original value. Although not exactly what they asked for, I believe this would help with [#88].

Small changes have been made to the selection boxes for opening the creature statblock, adjusting HP/status and the newly added AC feature. [#96]

To reflect strings being allowed in the AC field, the number validation for the AC field of players when setting up for parties has been removed. [#103]

Check-in to: master

### CODE REVIEW

**Comment by valentine195** [comment]
Hey I just pushed a (rather large, sorry) update that communizes the AC editing with HP and status.

Please take a look and see what you think.

**Comment by SondreElg** [comment]
Positives:
- It appears along with HP and status, so it's more obvious for new users that it exists
- Reset AC button is a nice addition

Negatives:
- It takes up more space/clutters the view
- Doesn't support strings as AC, e.g. "12 (15)" as a reminder for Mage Armor or the like

New bugs:
- Field does not default to DEFAULT_UNDEFINED if value is falsy
- [#96] is back

I must say I prefer the previous implementation, because of two primary reasons:
1. The Initiative Tracker view becomes very long very quickly, and adding more vertical elements makes it more difficult to keep track of what creatures have been added due to an AOE effect.
2. Compared to HP and statuses, you very rarely need to adjust AC, so most of the time the extra field is unneeded. Most common reason would be Mage Armor or equipping a shield, which I believe most would be content with either assuming is up, or writing as "12 (15)" or the like.

The previous implementation with the addition of the "Reset AC"-button I think would be perfect.

**Comment by valentine195** [comment]
Yeah, those points make sense. It can be made to support strings easy enough. 

I agree with the view becoming overly long. It is possible to move the creature updating subview to a modal, similar to the new add creature view. Or we open a new view, similar to the Combatant viewer.

I _think_ I would rather keep it in the HP/Status update just for consistency, and then everything flows through the tracker's updating.

**Comment by SondreElg** [comment]
We should now have the best of both worlds.

Easiest solution to my proposal was to add a separate updating category, `acUpdating` and move the logic for AC updates to its own functions in the tracker. Could probably find another more succinct solution, but my attempts to do so usually ended up in a lot of extra ifs, and this is much more easy to read than those alternatives.

**Comment by SondreElg** [comment]
Alright, that was much easier than I'd thought. Sorry for all the back and forth, I have a tendency to be a bit scatterbrained on low sleep.

**Comment by valentine195** [comment]
Gonna try to review this tomorrow morning

**Pull request merged**
